# fly.toml app configuration file generated for astrosocial on 2025-07-07T16:49:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'astrosocial'
primary_region = 'sjc'

[env]
  REFRESH_COOKIE_DOMAIN = 'astrosocial.fly.dev'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
