app = 'astrolounge-dev'
primary_region = 'sjc'

[env]
  REFRESH_COOKIE_DOMAIN = 'astrolounge-dev.fly.dev'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1